- src/css/custom.css
> changed font family

- docs/CLI.md
- docs/data_sources/datasource_plugins.md
- docs/event_sources/event_source_plugins.md
- docs/event_sources/overview.md
- docs/getting_started/Create sample blog project.md
- docs/getting_started/create hello-world project.md
- docs/getting_started/create_blog_project.md
- docs/getting_started/create_hello_world.md
- docs/getting_started/overview.md
- sidebars.js
updated sample projects and added latest cli terminal images
> updated sample projects

- docs/event_sources/standardized_event_schema.md
- docs/telemetry/overview.md
- docs/workflows/overview.md
> added workflows

- docs/data_sources/datasource_plugins.md
- docs/event_sources/event_source_plugins.md
- docs/event_sources/standardized_event_schema.md
- docs/workflows/overview.md
> Few changes

- .vscode/settings.json
- docs/data_sources/create_your_data_source.md
- docs/event_sources/create_your_event_source.md
- docs/getting_started/create_hello_world.md
> added replit

- docs/getting_started/create_hello_world.md
added replit in sample project page
> added replit in sample project page

- docs/Swagger_specs.md
- sidebars.js
> added swagger page

- docs/ai_modules/react_app.md
- sidebars.js
I have created a section called AI Modules - to saperate Godspeed AI Related Projects.
> gskit document added

- versioned_docs/version-v1/microservices/setup/debugger-in-yaml.md
- versioned_docs/version-v1/table-of-contents.md
- versioned_sidebars/version-v1-sidebars.json
> added debugger documentation

- docs/workflows/native_language_functions.md
native_workflow_ctx_indetailed
> native_workflow_ctx_indetailed

- versioned_docs/version-v1/microservices/setup/debugger-in-yaml.md
- versioned_docs/version-v1/microservices/workflows.md
updated ctx info in js/ts workflows v1
> updated ctx info in js/ts workflows v1

- docs/config/overview.md
- docs/data_sources/create_Datasource_plugin.md
- docs/design_principles.md
- docs/event_sources/create_eventsource_plugin.md
Embedded videos about guard rails in design_principles.
Added videos in datasource_plugin and eventsource_plugin
> Embedded videos

- docs/design_principles.md
- docs/event_sources/standardized_event_schema.md
- docs/introduction.md
- docs/tenets_and_design_principles.md
- sidebars.js
Tenets section shifted to design_principles
> fix:tenets section shifted to design_principles

- docs/introduction.md
- sidebars.js
CLI position is changed and few errors fixed
> CLI position is changed and few errors fixed

- docs/event_sources/event_source_plugins.md
added graphql eventsource in documentation
> added graphql eventsource in documentation

- docs/ai_modules/react_app.md
i updated the cli command (new ) in the gsKit.
> uiKit cli update

- docusaurus.config.js
- package-lock.json
- package.json
checking cmf-search , if it works online
> checking cmf-search

- docs/microservices-framework/event-sources/schema-validation.md
Added response and request schema validation along with examples and response images
> Updated the schema validation

- docs/microservices-framework/authentication/jwt-authentication.md
- docs/microservices-framework/authentication/overview.md
- docs/microservices-framework/datasources/create-custom-datasource.md
- docs/microservices-framework/datasources/overview.md
- sidebars.js
Authentication-folder-updated with Overview and JWT Authentication Subfolders and few other changes are made.
> Authentication-folder-updated

- docs/microservices-framework/inline-scripting/overview.md
- docs/microservices-framework/workflows/yaml-workflows/inbuilt-workflows.md
- docs/microservices-framework/workflows/yaml-workflows/workflow-dsl.md
Updated scriprting and on_error default value
> updated the default value

- docs/microservices-framework/authorization/authz-usecases.md
- docs/microservices-framework/getting-started/create-hello-world.md
- docs/microservices-framework/getting-started/overview.md
Swagger link is added in the overview
A note that authz notation is still under progress as pointed by gurjot is added
> Minor changes

- docs/microservices-framework/getting-started/overview.md
> correction in helloworld event

- sidebars.js
Removed 1. from Top level heading (Microservices framework)
> Branch1 (corrected sidebar numbering) 

- docs/microservices-framework/databases/PostgreSQL.md
- docs/microservices-framework/event-sources/validations/validation-error.md
This is the right way to get error message on response validation error
message: <% inputs.validation_error.data.message %>
> correction in validation_error

- docs/microservices-framework/authentication/custom-authentication.md
- docs/microservices-framework/databases/MariaDB.md
- docs/microservices-framework/databases/MySQL.md
- docs/microservices-framework/databases/Overview.md
- docs/microservices-framework/databases/PostgreSQL.md
- docs/microservices-framework/datasources/datasource-plugins/Prisma Datasource.md
- docs/microservices-framework/faqs.md
Added new examples in the "How To guide" section and improvements done in prisma plugin and db sections
> improvements in db and new guides

- docs/saarthi/basic-usage/using-modes.md
- Update cwd path to generic home dir 
- remove cog-wheel icon from MCP-setting to not confuse users 
- Update rag-mcp package link to godspeedsystems
> Chore: Update RAG-node documentation
